CREATE TABLE auth."users" (
                              "user_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                              "name" varchar,
                              "password" varchar NOT NULL,
                              "email" varchar NOT NULL,
                              "team" varchar,
                              "role" int NOT NULL,
                              "position" int NOT NULL,
                              "created_at" timestamp NOT NULL default now(),
                              "updated_at" timestamp NOT NULL default now()
);

CREATE TABLE auth."positions" (
                                  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                  "position_title" varchar NOT NULL
);

CREATE TABLE auth."user_roles" (
                                   "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                   "role_title" varchar NOT NULL
);

CREATE TABLE auth."role_permissions" (
                                         "permission_id" int NOT NULL,
                                         "role_id" int NOT NULL,
                                         PRIMARY KEY (permission_id, role_id)

);

CREATE TABLE auth."permissions" (
                                    "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                    "system" varchar NOT NULL,
                                    "action" varchar NOT NULL
);

ALTER TABLE auth.users ADD FOREIGN KEY ("role") REFERENCES auth."user_roles" ("id");
ALTER TABLE auth.users ADD FOREIGN KEY ("position") REFERENCES auth."positions" ("id");
ALTER TABLE auth."role_permissions" ADD FOREIGN KEY ("role_id") REFERENCES auth."user_roles" ("id");
ALTER TABLE auth."role_permissions" ADD FOREIGN KEY ("permission_id") REFERENCES auth."permissions" ("id");

CREATE TABLE resource_service."workplace" (
                                              "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                              "address" varchar NOT NULL,
                                              "zone" varchar NOT NULL,
                                              "floor" int NOT NULL,
                                              "number" int NOT NULL,
                                              "type" varchar NOT NULL,
                                              "capacity" int NOT NULL,
                                              "description" text,
                                              "is_available" boolean DEFAULT true,
                                              "maintainance_status" varchar,
                                              "created_at" timestamp NOT NULL default now(),
                                              "updated_at" timestamp NOT NULL default now(),
                                              "unique_tag" varchar UNIQUE NOT NULL
);
CREATE TABLE resource_service."item_conditions" (
                                                    "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                                    "value" varchar NOT NULL,
                                                    "description" text
);
INSERT INTO resource_service."item_conditions" (value, description) VALUES
('Хорошее', 'Не требует ремонта'),
('Плохое', 'Требует небольшого ремонта'),
( 'Ужасное', 'Требует большого ремонта');
CREATE TABLE resource_service."items" (
                                          "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                          "type" varchar NOT NULL,
                                          "name" varchar NOT NULL,
                                          "condition_id" int NOT NULL,
                                          "workplace_id" int,
                                          "created_at" timestamp NOT NULL default now(),
                                          "updated_at" timestamp NOT NULL default now(),
                                          FOREIGN KEY ("workplace_id") REFERENCES resource_service."workplace" ("id") ON DELETE SET NULL,
                                          FOREIGN KEY ("condition_id") REFERENCES resource_service."item_conditions" ("id")
);




Create table resource_service."parking_spaces"(
                                                  "id" int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                                  "address" varchar NOT NULL,
                                                  "zone" varchar NOT NULL,
                                                  "number" int NOT NULL,
                                                  "type" VARCHAR not null,
                                                  "is_available" boolean DEFAULT true,
                                                  "created_at" timestamp NOT NULL default now(),
                                                  "updated_at" timestamp NOT NULL default now()
);

CREATE INDEX idx_workplace_zone ON resource_service.workplace(zone);
CREATE INDEX idx_workplace_floor ON resource_service.workplace(floor);
CREATE INDEX idx_workplace_type ON resource_service.workplace(type);
CREATE INDEX idx_workplace_is_available ON resource_service.workplace(is_available);

CREATE INDEX idx_items_workplace_id ON resource_service.items(workplace_id);
CREATE INDEX idx_items_type ON resource_service.items(type);

CREATE TABLE booking_service."booking" (
                                           "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                           "user_id" int not null,
                                           "workplace_id" int not null,
                                           "start_date" timestamp not null,
                                           "end_date" TIMESTAMP not null,
                                           "status" varchar not null,
                                           "created_at" TIMESTAMP not null default now(),
                                           "updated_at" timestamp not null default now()
);

Create table booking_service."parking_bookings"(
                                                   "id" int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                                   "user_id" int NOT NULL,
                                                   "parking_space_id" int NOT NULL,
                                                   "start_date" timestamp NOT NULL,
                                                   "end_date" timestamp NOT NULL,
                                                   "status" VARCHAR not null,
                                                   "created_at" TIMESTAMP NOT NULL default now(),
                                                   "updated_at" timestamp not null default now(),
                                                   FOREIGN KEY ("parking_space_id") REFERENCES resource_service.parking_spaces ("id") ON DELETE SET NULL
);

ALTER TABLE booking_service."booking" ADD FOREIGN KEY ("user_id") REFERENCES auth."users" ("user_id");
ALTER TABLE booking_service."booking" ADD CONSTRAINT check_booking_dates
    CHECK (end_date > start_date);
ALTER TABLE booking_service."booking" ADD FOREIGN KEY ("workplace_id") REFERENCES resource_service.workplace ("id");

ALTER TABLE booking_service."parking_bookings" ADD FOREIGN KEY ("user_id") REFERENCES auth.users ("user_id");