CREATE TABLE "workplace" (
                             "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                             "address" varchar,
                             "zone" varchar,
                             "number" int,
                             "features" varchar,
                             "type" varchar,
                             "capacity" int
);

CREATE TABLE "users" (
                         "user_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                         "name" varchar,
                         "email" varchar,
                         "team" varchar,
                         "role" int,
                         "position" int
);

CREATE TABLE "booking" (
                           "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                           "userID" int,
                           "workplaceID" int,
                           "date" timestamp,
                           "status" varchar
);

CREATE TABLE "positions" (
                             "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                             "position_title" varchar
);

CREATE TABLE "parking_lots" (
                                "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                "number" int,
                                "userID" int,
                                "date" timestamp,
                                "status" varchar
);

CREATE TABLE "user_roles" (
                              "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                              "role_title" varchar
);

CREATE UNIQUE INDEX ON "workplace" ("address", "zone", "number");

ALTER TABLE "users" ADD FOREIGN KEY ("position") REFERENCES "positions" ("id");

ALTER TABLE "booking" ADD FOREIGN KEY ("userID") REFERENCES "users" ("user_id");

ALTER TABLE "booking" ADD FOREIGN KEY ("workplaceID") REFERENCES "workplace" ("id");

ALTER TABLE "parking_lots" ADD FOREIGN KEY ("id") REFERENCES "users" ("user_id");

ALTER TABLE "users" ADD FOREIGN KEY ("role") REFERENCES "user_roles" ("id");
